language: node_js
node_js:
  - '12.16.1'
branches:
  only:
    - master
sudo: true

addons:
    chrome: stable

cache:
  directories:
    - ./node_modules

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

install:
  - npm install

script:
  - ng test --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - ng build --prod
  
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
