language: node_js
node_js:
  - '12.16.1'
branches:
  only:
    - master
sudo: true

addons:
    chrome: stable

cache:
  directories:
    - ./node_modules
    
jobs:
  include:
    - stage: test
      script:
       - npm install -g @angular/cli
       - ng test --watch=false --no-progres -browsers=ChromeHeadlessNoSandbox
       - ng build --prod
    - stage: deploy
      script:
        - npm install -g firebase-tools
        - firebase deploy --token $FIREBASE_TOKEN
        
 stages:
  - name: test
    if: type = pull_request
  - name: deploy
    if: type = push AND branch = master
